# add this to your configuration.yaml

ev_charger_modbus:
  port: /dev/ttyUSB0  # Adjust to your USB port
  name: EV Charger    # Optional
  slave: 1            # Optional
  baudrate: 38400     # Optional

logger:
  default: info
  logs:
    custom_components.ev_charger_modbus: debug
